// Mocks generated by Mockito 5.4.6 from annotations
// in countries/test/home/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:countries/coor/use_case/use_cases.dart' as _i7;
import 'package:countries/features/home/domain/entities/entities.dart' as _i6;
import 'package:countries/features/home/domain/repository/repository.dart'
    as _i2;
import 'package:countries/features/home/domain/usecases/get_countries_api.dart'
    as _i4;
import 'package:countries/features/home/domain/usecases/get_countries_local.dart'
    as _i8;
import 'package:countries/networking/api_result.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCountriesRemoteHomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountriesRemoteHomeUseCase extends _i1.Mock
    implements _i4.GetCountriesRemoteHomeUseCase {
  @override
  _i2.HomeRepository get homeRepos =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepos),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepos),
            ),
            returnValueForMissingStub: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepos),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.Country>>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.ApiResult<List<_i6.Country>>>.value(
              _FakeApiResult_1<List<_i6.Country>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.ApiResult<List<_i6.Country>>>.value(
                  _FakeApiResult_1<List<_i6.Country>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.ApiResult<List<_i6.Country>>>);
}

/// A class which mocks [GetCountriesLocalHomeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountriesLocalHomeUseCase extends _i1.Mock
    implements _i8.GetCountriesLocalHomeUseCase {
  @override
  _i2.HomeRepository get homeRepos =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepos),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepos),
            ),
            returnValueForMissingStub: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepos),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<List<_i6.Country>?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<List<_i6.Country>?>.value(),
            returnValueForMissingStub: _i5.Future<List<_i6.Country>?>.value(),
          )
          as _i5.Future<List<_i6.Country>?>);
}
